### ISSUE TITLE
File size as extension

### ISSUE THREAD

**Issue by cameloper** [DeOldSax/iliasDownloaderTool#25]
### Steps that lead to issue

1. Opened iliasDownloaderTool
2. Logged in using 'Anmelden' button
3. Did a sync
4. Downloaded a specific file

### Expected Result
iliasDownloaderTool downloads the missing files with correct name and extension to the previously given path.

### What really happened
Although file name is correct, the downloaded file has its size as extension.
i.e. 
<img width="116" alt="image" src="https://user-images.githubusercontent.com/12815570/52534963-a293c800-2d48-11e9-81fb-4370129c11cd.png">

### Specs
 - System: macOS Mojave
 - iliasDownloaderTool version: v1.2.0
 - JRE version 1.8.0_191

**Comment by DeOldSax** [comment]
@cameloper which university? Karlsruhe, Tübingen or Stuttgart?

**Comment by DeOldSax** [comment]
easy fix with credentials:
https://github.com/DeOldSax/iliasDownloaderTool/blob/5cf7e506fd124b1c09a727def1bbf110a2b08925/src/main/java/control/IliasScraper.java#L167

**Comment by cameloper** [comment]
> @cameloper which university? Karlsruhe, Tübingen or Stuttgart?

Karlsruhe. 



> easy fix with credentials:
> 
> [iliasDownloaderTool/src/main/java/control/IliasScraper.java](https://github.com/DeOldSax/iliasDownloaderTool/blob/5cf7e506fd124b1c09a727def1bbf110a2b08925/src/main/java/control/IliasScraper.java#L167)
> Line 167 in [5cf7e50](/DeOldSax/iliasDownloaderTool/commit/5cf7e506fd124b1c09a727def1bbf110a2b08925)
>  fileExtension = children.get(i - 1).text().replace("\u00a0", "").trim();

will try this!

The issue started occurring suddenly. After the last update, I've used the current version without any problems for a while. Any idea what could be the cause?

**Comment by DeOldSax** [comment]
> Any idea what could be the cause?
Either updates on the html representation or a new / special case i did not take care of in my regex.

I remember this bug happened some time ago. Checking the history of the referenced file will give you some insights :)

**Comment by cameloper** [comment]
> Checking the history of the referenced file will give you some insights :)

Alright, thanks a lot!

**Comment by DeOldSax** [comment]
https://github.com/DeOldSax/iliasDownloaderTool/commit/96f834d18ec8ed2b5fdb6bb1169701e968a7c683

**Comment by DeOldSax** [comment]
95fa310
