### ISSUE TITLE
Nullpointer Error at login for University of Tuebingen

### ISSUE THREAD

**Issue by TheSalocin** [DeOldSax/iliasDownloaderTool#41]
Version: tueb-v1.2.2
Java version: 1.8.0_251

Console output:
 

>  WARN [main] (Dashboard.java:65) - Start IliasDownloaderTool.

>Apr 22, 2020 10:41:10 AM javafx.scene.CssStyleHelper calculateValue
>WARNING: Could not resolve '-fx-control-inner-background' while resolving lookups for '-fx-highlight-fill' from rule '*.custom-text-field' in stylesheet jar:file:filepath/IliasDownloaderTool-tueb-v1.2.2/lib/controlsfx-8.20.8.jar!/org/controlsfx/control/textfield/customtextfield.bss
>Apr 22, 2020 10:41:10 AM javafx.scene.CssStyleHelper calculateValue
>WARNING: Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-highlight-text-fill' from rule '*.custom-text-field' in stylesheet jar:file:filepath/IliasDownloaderTool-tueb-v1.2.2/lib/controlsfx-8.20.8.jar!/org/controlsfx/control/textfield/customtextfield.bss
>Exception in thread "Thread-4" java.lang.NullPointerException
>	at plugin.TuebIlias.login(TuebIlias.java:44)
>	at control.IliasManager.login(IliasManager.java:31)
>	at control.IliasStarter.login(IliasStarter.java:30)
>	at control.LoginProvider$1.run(LoginProvider.java:53)
>	at java.lang.Thread.run(Thread.java:748)

**Comment by Clausinho** [comment]
i assume close means nofix?

**Comment by Clausinho** [comment]
I get the following error:
```
 java -jar C:\Users\Clausi\Downloads\IliasDownloaderTool-tueb-v1.2.2\Ilias-Downloader-Tool-tueb-v1.2.2.jar
 WARN [main] (Dashboard.java:65) - Start IliasDownloaderTool.
Feb 06, 2021 3:57:23 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-control-inner-background' while resolving lookups for '-fx-highlight-fill' from rule '*.custom-text-field' in stylesheet jar:file:/C:/Users/Clausi/Downloads/IliasDownloaderTool-tueb-v1.2.2/lib/controlsfx-8.20.8.jar!/org/controlsfx/control/textfield/customtextfield.bss
Feb 06, 2021 3:57:23 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Could not resolve '-fx-text-inner-color' while resolving lookups for '-fx-highlight-text-fill' from rule '*.custom-text-field' in stylesheet jar:file:/C:/Users/Clausi/Downloads/IliasDownloaderTool-tueb-v1.2.2/lib/controlsfx-8.20.8.jar!/org/controlsfx/control/textfield/customtextfield.bss
Exception in thread "Thread-5" java.lang.NullPointerException
        at plugin.TuebIlias.login(TuebIlias.java:44)
        at control.IliasManager.login(IliasManager.java:31)
        at control.IliasStarter.login(IliasStarter.java:30)
        at control.LoginProvider$1.run(LoginProvider.java:53)
        at java.lang.Thread.run(Unknown Source)
```
So https://github.com/DeOldSax/iliasDownloaderTool/pull/39 does not fix the nullpointer anymore I assume.
Maybe @Tyxz has some advice?

**Comment by Clausinho** [comment]
Well, should've read the whole README. #39 is not in the release yet.
I built the downloader using sdkman (using the new sdk java 8.0.282.fx-zulu" and the develop branch, so now it seems I'm logged in. Actually getting the courses seems to be a challenge. Didn't work with https://github.com/thetric/ilias-downloader-cli/releases/tag/v4.1.0-beta.1 too. I might be able to dedicate some time into this after the exams and after understanding the codebase.
