### ISSUE TITLE
Login try gets blocked with notification "Wrong password" for KIT Ilias

### ISSUE THREAD

**Issue by PaulHasAProblem** [DeOldSax/iliasDownloaderTool#52]
Hey there,

since a few days I am not longer able to use the downloader tool because I get a wrong password notification in the downloader tool (password is definitly correct). Even if I use the less secure connection I am not able to connect.
I am not sure if it helps you but I attached the command line with throws some exceptions.

Thanks for your help!

![grafik](https://user-images.githubusercontent.com/67016185/103541993-8c430800-4e9c-11eb-824a-e8fe05a1379b.png)

**Comment by DeOldSax** [comment]
thx for the comment. I suspect that the structure of the login page has changed. Maybe someone using the login can have a look at this?
