### ISSUE TITLE
"String input must not be null"

### ISSUE THREAD

**Issue by freedome97** [DeOldSax/iliasDownloaderTool#54]
In a recent issue (#52 ), the login for KIT Illias wasn't working. Thankfully it got patched and seems to work.

But I compiled the new source code and since then I receive an Null-String Error while the structure is building.
Tried to backtrace and fix it but did not find the solution. Any ideas?

![StringNull](https://user-images.githubusercontent.com/50106400/104017045-b441ac80-51b7-11eb-8f74-20883d9aaa6c.png)

**Comment by DeOldSax** [comment]
- which branch are you trying to build?
- against which jdk version?
- did you try to delete the settings folder? --> `C:\Users\%USERNAME%\.ilias`

**Comment by freedome97** [comment]
Sorry, forgot to mention those. This is my first issue on GitHub.

- I built the "develop" branch since it´s the only one with the fix for "KIT Illias"
- echo %java_home% >> jdk1.8.0_271
- Yes, and it threw more errors, saying that it´s missing those files:
![FileMissing](https://user-images.githubusercontent.com/50106400/104052097-79f10300-51e9-11eb-8f85-c7665ee4d2cc.png)

**Comment by DeOldSax** [comment]
looks good - if you start again the errors should go away (they are not a problem at all;)) 
does it work now?

**Comment by freedome97** [comment]
Yeah I know, just a hint for eventual except-handlers :D
And No :/ The "Refresh"-Button will keep spinning and nothings happens (No displayed courses or downloadable content).
Everything worked just fine before KIT changed their login thingy.

**Comment by freedome97** [comment]
Update: This is odd. It seems like the String is Null, since the parser can not find any "h4" references inside the document/webpage provided.

Interestingly, even tough the program says that I am "successfully logged in", the webpage it is parsing is the one from the University Konstanz and not Karlsruhe. Therefore lands on the main page and due to fail in login can not parse.

![konstanz2](https://user-images.githubusercontent.com/50106400/104310480-152cf580-54d4-11eb-9985-fbc2532c8f34.png)

![konstanz](https://user-images.githubusercontent.com/50106400/104310486-178f4f80-54d4-11eb-8d3f-b11dd96074bf.png)

Any idea how to fix this? Sadly, I have no idea in HTML programming or where this error could come from.
Greetings

**Comment by DeOldSax** [comment]
- check if you changed the value of project.university to `kit` here: https://github.com/DeOldSax/iliasDownloaderTool/blob/c7ca12a5ef6df8bbf55c142f29ad540bc6f3e547/pom.xml#L12
- check if you have the right plugin class here: https://github.com/DeOldSax/iliasDownloaderTool/blob/c7ca12a5ef6df8bbf55c142f29ad540bc6f3e547/src/main/java/control/IliasManager.java#L14

I guess there is the problem. Changing this params might not be that obvious from the documentation - should be added probably :)

**Comment by freedome97** [comment]
I knew I had to change something, but did not find the second change I had to make.
Works now. Thanks for the help 👍 :)
